customhost = "employee.c0ruga5hoej8.us-east-2.rds.amazonaws.com"
customuser = "erickemvou"
custompass = "abc123abc123"
customdb = "employee"
custombucket = "lasserfocusclass"
customregion = "us-east-2"
